# P6 Data Processing - Entity Resolution

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from glob import glob

pd.set_option("display.max_columns", 100)

In [2]:
DATA_DIR = os.path.join(os.environ["HOME"], "Datasets", "HTX_Hackathon","ps6-entityres")

# Read JSON

In [6]:
train_json = pd.read_json(os.path.join(DATA_DIR, "train_small.json"), lines=True)
valid_json = pd.read_json(os.path.join(DATA_DIR, "valid_small.json"), lines=True)

display(train_json.shape)
display(train_json.head())

display(valid_json.shape)
display(valid_json.head())

(1804, 18)

,pair_id,label,id_left,category_left,cluster_id_left,brand_left,title_left,description_left,price_left,specTableContent_left,id_right,category_right,cluster_id_right,brand_right,title_right,description_right,price_right,specTableContent_right
0,17014053#13812379,0,17014053,Jewelry,11012750,"""Rolex""","""Rolex Milgauss 116400 GV"" GV Watch | Watchfi...","""This Rolex has undergone a thorough inspectio...",None,None,13812379,Jewelry,3893035,"""Cartier""","""Cartier Roadster W62004V3"" W62004V3 Watch | ...","""This Cartier has undergone a thorough inspect...",None,Name Monthly Repayment Total Amount Cost of C...
1,15045487#1567262,0,15045487,Jewelry,454804,None,""" Daniel Wellington Men's Cambridge Silver 40...","""This slim-line gents Daniel Wellington Cambri...",None,None,1567262,Jewelry,664971,"""Daniel Wellington""@es","""York Silver Reloj para mujer 36mm""@es ""Danie...",None,None,None
2,9571796#12112900,0,9571796,Jewelry,10459518,None,""" Mens Marea Watch 54088/3 ""All Watches""",None,None,None,12112900,Jewelry,1642088,None,""" Ladies Karl Lagerfeld Joleigh Watch KL3409 ...",None,None,None
3,14251295#3322087,0,14251295,Jewelry,635138,"""Junghans""@de","""Automatikuhr Max Bill""@de ""Junghans Automati...","""\n\t\t\t\t\tArtikel-Nr.: 3522 027/4700.00\n\t...",None,None,3322087,Jewelry,255636,None,"""Max Bill Automatic Acier/Noir - Junghans""@fr...","""\n\n\t\t\t\t\t\t\tRétro et épurée, cette mont...",None,Genre Mixte Âge Adulte Boitier Acier inoxydab...
4,769348#10589615,1,769348,Jewelry,1491262,None,""" M200 Bluetooth GPS Activity Tracker Heart R...",None,None,None,10589615,Jewelry,1491262,None,""" Unisex Polar M200 Bluetooth GPS Activity Tr...",None,None,None

(451, 18)

,pair_id,label,id_left,category_left,cluster_id_left,brand_left,title_left,description_left,price_left,specTableContent_left,id_right,category_right,cluster_id_right,brand_right,title_right,description_right,price_right,specTableContent_right
0,12091517#13483606,0,12091517,Jewelry,111879,None,"""Montre Tissot T-TOUCH EXPERT SOLAR / Acier R...",None,None,None,13483606,Jewelry,607687,"""Tissot""@pl","""Quickster Chronograf męski""@pl 00 €""@pl ""Tis...",None,None,Ogólny specjalny: Swiss Made rodzaj: chronogr...
1,1015551#9253029,1,1015551,Jewelry,510534,None,""" Daniel Wellington Men's Sheffield 40mm Watc...","""This slim-line gents Daniel Wellington Sheffi...",None,None,9253029,Jewelry,510534,None,"""Herren Daniel Wellington Sheffield 40mm Uhr ...",None,None,None
2,6289257#11980523,1,6289257,Jewelry,4284548,None,"""Maurice Lacroix Les Classiques Watch LC1087-...","""<p> At Costello Jewelry Company in Naperville...",None,None,11980523,Jewelry,4284548,None,"""Maurice Lacroix Les Classiques Watch LC1087-...","""<p> At Costello Jewelry Company in Naperville...",None,None
3,12989983#12647769,1,12989983,Jewelry,1435236,"""Diesel""@es","""Mr. Daddy 2.0 Reloj para hombre""@es ""Diesel ...",None,None,None,12647769,Jewelry,1435236,"""Diesel""@pl","""Mr. Daddy 2.0 Zegarek męski""@pl 00 €""@pl ""Di...",None,None,None
4,7885959#10675205,0,7885959,Jewelry,11213997,None,"""Cartier Santos 100 Watch W20073X8"" ""Shop Car...","""<p>This fine watch, model number W20073X8 fro...",None,None,10675205,Jewelry,11216891,None,"""Cartier Santos 100 Automatic Large Steel and...",None,None,Brand: Cartier Collection: Santos 100 Model N...

# Write Raw Data to CSV

In [7]:
train_json.to_csv(os.path.join(DATA_DIR, "train_small.csv"), index = False)
valid_json.to_csv(os.path.join(DATA_DIR, "valid_small.csv"), index = False)